#!/bin/bash

echo "==============================================="
echo "  Alias Scripts ......"
echo "==============================================="
cat >> ~/.bashrc <<EOF
alias cat=ccat
EOF
echo "alias s5='s5cmd'" | tee -a ~/.bashrc
echo "alias c='clear'" | tee -a ~/.bashrc
echo "alias b='/bin/bash'" | tee -a ~/.bashrc
echo "alias cs='cd /home/ec2-user/SageMaker'" | tee -a ~/.bashrc
echo "alias cls='conda env list'" | tee -a ~/.bashrc
echo "alias sa='source activate JupyterSystemEnv'" | tee -a ~/.bashrc
echo "alias sd='source deactivate'" | tee -a ~/.bashrc
echo "alias rr='sudo systemctl daemon-reload; sudo systemctl restart jupyter-server'" | tee -a ~/.bashrc


echo "==============================================="
echo "  Cofing dfimage ......"
echo "==============================================="
cat >> ~/.bashrc <<EOF
alias dfimage="docker run -v /var/run/docker.sock:/var/run/docker.sock --rm alpine/dfimage"  
EOF
source ~/.bashrc
# dfimage -sV=1.36 nginx:latest 


echo "==============================================="
echo "  Install yq for yaml processing ......"
echo "==============================================="
echo 'yq() {
  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}' | tee -a ~/.bashrc && source ~/.bashrc


echo "==============================================="
echo "  Path ......"
echo "==============================================="
# Go
export GOPATH=$(go env GOPATH)
echo 'export GOPATH='${GOPATH} >> ~/.bashrc
echo 'export PATH=$PATH:$GOPATH/bin' >> ~/.bashrc
# pyenv
echo "export PYENV_ROOT=$HOME/.pyenv" | tee -a ~/.bashrc
echo "export PATH=$HOME/.pyenv/bin\:$PATH" | tee -a ~/.bashrc
eval "$($HOME/.pyenv/bin/pyenv init -)"
# custom
echo 'export PATH=$PATH:/home/ec2-user/SageMaker/custom' >> ~/.bashrc


echo "==============================================="
echo "  Auto Stop ......"
echo "==============================================="
# auto stop idle
IDLE_TIME=10800 # 3600 28800
echo "Detecting Python install with boto3 install"
# Find which install has boto3 and use that to run the cron command. So will use default when available
# Redirect stderr as it is unneeded
CONDA_PYTHON_DIR=$(source /home/ec2-user/anaconda3/bin/activate /home/ec2-user/anaconda3/envs/JupyterSystemEnv && which python)
if $CONDA_PYTHON_DIR -c "import boto3" 2>/dev/null; then
    PYTHON_DIR=$CONDA_PYTHON_DIR
elif /usr/bin/python -c "import boto3" 2>/dev/null; then
    PYTHON_DIR='/usr/bin/python'
else
    # If no boto3 just quit because the script won't work
    echo "No boto3 found in Python or Python3. Exiting..."
    exit 1
fi
echo "Found boto3 at $PYTHON_DIR"
echo "Starting the SageMaker autostop script in cron"
(crontab -l 2>/dev/null; echo "*/5 * * * * $PYTHON_DIR /home/ec2-user/SageMaker/custom/autostop.py --time $IDLE_TIME --ignore-connections >> /var/log/jupyter.log") | crontab -

