#!/bin/bash

sudo -u ec2-user -i <<'EOF'
unset SUDO_UID

WORKING_DIR=/home/ec2-user/SageMaker/custom
source "$WORKING_DIR/miniconda/bin/activate"

for env in $WORKING_DIR/miniconda/envs/*; do
    BASENAME=$(basename "$env")
    # source activate "$BASENAME"
    python -m ipykernel install --user --name "$BASENAME" --display-name "custom_$BASENAME"
    # python -m ipykernel install --user --name "$BASENAME"    
done

# Optionally, uncomment these lines to disable SageMaker-provided Conda functionality.
# echo "c.EnvironmentKernelSpecManager.use_conda_directly = False" >> /home/ec2-user/.jupyter/jupyter_notebook_config.py
# cp /home/ec2-user/.condarc /home/ec2-user/.condarc.backup
# rm /home/ec2-user/.condarc
# if uncomment, will erase braket
EOF